# Generated by Django 6.0 on 2026-01-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='quiz',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_image'),
        ),
    ]
